name: Flutter Web Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 💽 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🔨 Build Web
        run: flutter build web --release

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: build/web/
          server-dir: / # যদি আপনার ফাইল public_html এ থাকে তবে এখানে /public_html/ লিখুন
          # টাইমআউট সমস্যা এড়াতে নিচের অপশনটি যোগ করা হয়েছে
          timeout: 60000 
          # লগ ডিবাগ করার জন্য
          log-level: verbose
