name: Flutter Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-web:
    name: Build & Deploy Web to cPanel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href=/

      # SSH Setup
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 209.74.67.35 >> ~/.ssh/known_hosts

      # Deploy to cPanel public_html
      - name: Deploy to cPanel
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" \
          build/web/ \
          ltcmlgtn@209.74.67.35:/home/ltcmlgtn/ssh/
